name: PunishCheese
main: me.pix7.punishcheese.PunishCheese
version: 1
author: PixelArt7

commands:
  punishcheese:
    description: Show all commands in this plugin.
    usage: /punishcheese
    permission: punishcheese.admin
    permission-message: You don't have permissions.
  addrule:
    description: Add rule to database.
    usage: /addrule <RuleId> <Short-Description>
    permission: punishcheese.admin
    permission-message: You don't have permissions.
  addruledetail:
    description: Add rule detail to database.
    usage: /addruledetail <RuleId> <Description>
    permission: punishcheese.admin
    permission-message: You don't have permissions.
  rules:
    description: Show all rules of this server.
    usage: /rules
    permission: punishcheese.member
    permission-message: You don't have permissions.
  punish:
    description: Apple punishment to player.
    usage: /punish - to view usage.
    permission: punishcheese.admin
    permission-message: You don't have permissions.